### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by necropola** [MrGunflame/gw2api#1]
Hi,

while trying to implement my own little golang client for the official GW2 Web API I found your project and an older one by someone else (https://github.com/yasvisu/gw2api) which is the one mentioned on the  gw2wiki.

* Are you still working on / maintaining this project?
* If yes, which is the main upstream repo (this or the one on gitlab)?

I admit that after being very hyped in the beginning (golang is really a nice language to implement this kind of stuff), I'm already a bit frustrated due to how inconsistent, undocumented, incomplete and slow the official API is.

This (https://github.com/necropola/MMO-Casuals/tree/main/gw2builds) is my current playground. The actual goal is/was to create a Static Website Armory for all my characters and some additional pages about general open world builds. Either by using **hugo** (why do they have such terrible documentation?) or by using golang's httml templates directly (much better documentation).

I think you did a pretty good job with your wrapper as far as I can see.

I also found your golang gw2 discord bot on gitlab (https://gitlab.com/MrGunflame/robbot) which is also an idea I have been thinking about myself. And/or exposing some of the information retrieved from the gw2api via discord's rich presence (old school via IPC in golang and not via their SDK)

Thanks and cheers.

**Comment by MrGunflame** [comment]
Hi and thanks for opening this issue,

I need to admit that I haven't touched this one since some time, the main reason is the weak documentation of the API, however with the slow pace the API being updated it should still work fine for 99% of the wrapper. I'm still using it. so I'll keep the most important parts up to date (that's worlds, wvw, trading post and guilds for me), but if you find that something is missing or wrong, feel free to open an issue or PR and I'll get around and add/update it.

The GitLab is the upstream repo, but both should work just fine when imported in Go.
